<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.33">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Bradley Allen and Sam Parker">
<meta name="dcterms.date" content="2026-07-27">

<title>Red State, Blue State, Mental State – Blitz Bearcat</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-ea385d0e468b0dd5ea5bf0780b1290d9.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-a591e4438404966679ba696034816107.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Blitz Bearcat</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../capstone.html"> 
<span class="menu-text">Capstone</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../resume.html"> 
<span class="menu-text">Resume</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/your_github_username"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://linkedin.com/in/your_github_username"> <i class="bi bi-linkedin" role="img" aria-label="LinkedIn">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction-and-background" id="toc-introduction-and-background" class="nav-link active" data-scroll-target="#introduction-and-background">Introduction and Background</a>
  <ul class="collapse">
  <li><a href="#analysis-of-other-potential-causes-of-anxiety-and-depression" id="toc-analysis-of-other-potential-causes-of-anxiety-and-depression" class="nav-link" data-scroll-target="#analysis-of-other-potential-causes-of-anxiety-and-depression">Analysis of Other Potential Causes of Anxiety and Depression</a></li>
  </ul></li>
  <li><a href="#method" id="toc-method" class="nav-link" data-scroll-target="#method">Method</a>
  <ul class="collapse">
  <li><a href="#python-packages" id="toc-python-packages" class="nav-link" data-scroll-target="#python-packages">Python Packages</a></li>
  <li><a href="#datasets-measures" id="toc-datasets-measures" class="nav-link" data-scroll-target="#datasets-measures">Datasets &amp; Measures</a>
  <ul class="collapse">
  <li><a href="#cdc-household-pulse-survey" id="toc-cdc-household-pulse-survey" class="nav-link" data-scroll-target="#cdc-household-pulse-survey"><em>CDC Household Pulse Survey</em></a></li>
  <li><a href="#google-search-trends" id="toc-google-search-trends" class="nav-link" data-scroll-target="#google-search-trends"><em>Google Search Trends</em></a></li>
  <li><a href="#abortion-restrictions" id="toc-abortion-restrictions" class="nav-link" data-scroll-target="#abortion-restrictions"><em>Abortion Restrictions</em></a></li>
  <li><a href="#state-political-leanings" id="toc-state-political-leanings" class="nav-link" data-scroll-target="#state-political-leanings"><em>State Political Leanings</em></a></li>
  </ul></li>
  </ul></li>
  <li><a href="#procedure" id="toc-procedure" class="nav-link" data-scroll-target="#procedure">Procedure</a>
  <ul class="collapse">
  <li><a href="#search-trends-analysis" id="toc-search-trends-analysis" class="nav-link" data-scroll-target="#search-trends-analysis">Search Trends Analysis</a></li>
  <li><a href="#exploratory-data-analysis" id="toc-exploratory-data-analysis" class="nav-link" data-scroll-target="#exploratory-data-analysis">Exploratory Data Analysis</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a>
  <ul class="collapse">
  <li><a href="#data-analysis-and-interpretation" id="toc-data-analysis-and-interpretation" class="nav-link" data-scroll-target="#data-analysis-and-interpretation">Data Analysis and Interpretation</a></li>
  <li><a href="#multiple-regression" id="toc-multiple-regression" class="nav-link" data-scroll-target="#multiple-regression">Multiple Regression</a>
  <ul class="collapse">
  <li><a href="#identification-of-variables" id="toc-identification-of-variables" class="nav-link" data-scroll-target="#identification-of-variables">Identification of Variables</a></li>
  <li><a href="#variable-1-time-period" id="toc-variable-1-time-period" class="nav-link" data-scroll-target="#variable-1-time-period"><em>Variable 1: Time Period</em></a></li>
  <li><a href="#variable-2-political-leaning" id="toc-variable-2-political-leaning" class="nav-link" data-scroll-target="#variable-2-political-leaning"><em>Variable 2: Political Leaning</em></a></li>
  <li><a href="#multiple-regression-model" id="toc-multiple-regression-model" class="nav-link" data-scroll-target="#multiple-regression-model">Multiple Regression Model</a></li>
  <li><a href="#check-for-linearity" id="toc-check-for-linearity" class="nav-link" data-scroll-target="#check-for-linearity">Check for Linearity</a></li>
  <li><a href="#independent-samples-t-test" id="toc-independent-samples-t-test" class="nav-link" data-scroll-target="#independent-samples-t-test">Independent Samples t-Test</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a>
  <ul class="collapse">
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations">Limitations</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Red State, Blue State, Mental State</h1>
<p class="subtitle lead">The Psychological Impact of Dobbs v. Jackson on Americans Across the Political Divide</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Bradley Allen and Sam Parker </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 27, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction-and-background" class="level1">
<h1>Introduction and Background</h1>
<p>Throughout American history, the Supreme Court has played a key role in shaping legal precedent, with far-ranging consequences for Americans. The Court has affirmed hard-won human rights, such as same-sex marriage in <em>Obergefell v. Hodges</em> <span class="citation" data-cites="fredrickson_obergefell_nodate">(<a href="#ref-fredrickson_obergefell_nodate" role="doc-biblioref">Fredrickson &amp; Wurman, n.d.</a>)</span>, and has also handed down decisions denying rights such as citizenship of a freed slave in <em>Dredd Scott v. Sandford</em> <span class="citation" data-cites="historycom_editors_dred_2009">(<a href="#ref-historycom_editors_dred_2009" role="doc-biblioref">History.com Editors, 2009</a>)</span>. Many of the Court’s decisions have a real and immediate impact on the American public. The <em>Dredd Scott</em> decision, for example, created immense public outrage, and is seen as one of the key events leading up to the American Civil War <span class="citation" data-cites="historycom_editors_dred_2009">(<a href="#ref-historycom_editors_dred_2009" role="doc-biblioref">History.com Editors, 2009</a>)</span>. As such, it is reasonable to infer that any major Supreme Court decision may induce anxiety and stress in adults.</p>
<p>In 2022, the Supreme Court ruled on another landmark case, <em>Dobbs v. Jackson</em>, that overturned five decades of precedent established by <em>Roe v. Wade</em>, putting the question of legal abortion to the States <span class="citation" data-cites="palacio_implications_2023">(<a href="#ref-palacio_implications_2023" role="doc-biblioref">Palacio, 2023</a>)</span>. According to the Kaiser Family Foundation <span class="citation" data-cites="kaiser_family_foundation_abortion_2025">(<a href="#ref-kaiser_family_foundation_abortion_2025" role="doc-biblioref">2025</a>)</span>, access to abortion varies by state and exists on a continuum ranging from a total ban to no gestational limits. Given this spectrum of access, it is reasonable to infer that anxiety and depressive symptoms may have been heightened in states where abortion was banned compared to states with fewer restrictions.</p>
<p>Access to abortion is generally understood as varying by political philosophy. According to a Pew Research Center poll <span class="citation" data-cites="pew_research_center_public_2025">(<a href="#ref-pew_research_center_public_2025" role="doc-biblioref">2025</a>)</span>, party affiliation dramatically affects views on abortion, with 57% of Republicans responding that “abortion should be <em>illegal</em> [emphasis added] in all / most cases” and 85% of Democrats maintaining that “abortion should be <em>legal</em> [emphasis added] in all / most cases.” Given this political split, it is likely that the <em>Dobbs v. Jackson</em> decision impacted anxiety rates differently in the most conservative states versus the least conservative states.</p>
<p>The present analysis aims to understand whether levels of anxiety and depression differed for adults living in the top 5 most conservative (conservative) vs.&nbsp;the top 5 least conservative (liberal) states during and after the <em>Dobbs</em> decision, and especially in the wake of related legal restrictions on reproductive rights. To assess this relationship, we will compare anxiety / depression scores in conservative states to liberal states, whose abortion restrictions range from abortion ban (most conservative) to low or no restriction (least conservative) during three times: <em>Before Dobbs</em>, <em>During Dobbs</em> and <em>After Dobbs</em>. We hypothesize that anxiety and depression levels in more conservative states will differ from those in less conservative states during the leak and the decision, but approximately the same before and after.</p>
<section id="analysis-of-other-potential-causes-of-anxiety-and-depression" class="level2">
<h2 class="anchored" data-anchor-id="analysis-of-other-potential-causes-of-anxiety-and-depression">Analysis of Other Potential Causes of Anxiety and Depression</h2>
<p>To ensure there were no confounding events, we explored major events at both the national (<strong><a href="#table-1-major-u.s.-events-in-2022">Table 1</a></strong>) and state levels (<strong><a href="#table-2-major-events-by-state-in-2022-bullock_major_nodate">Table 2</a></strong>) in and around the periods of interest and concluded that no significant events co-occurred with the Dobbs decision. Thus, the states we chose differ in level of access to abortion (e.g., either low restrictions or total ban), while unrelated issues (e.g., cost of living, crime) would be normative in each state and unlikely to covary with abortion as a predictor of anxiety and depression symptoms.</p>
<section id="table-1-major-events-in-the-u.s.-in-2022" class="level4">
<h4 class="anchored" data-anchor-id="table-1-major-events-in-the-u.s.-in-2022"><strong>Table 1</strong>: Major Events in the U.S. in 2022</h4>
<div id="a9fd2247" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="4">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Date</th>
<th style="text-align: left;">Event</th>
<th style="text-align: left;">Source</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Feb.&nbsp;24</td>
<td style="text-align: left;">Russia invades Ukraine</td>
<td style="text-align: left;">Latour and Crisp <span class="citation" data-cites="latour_biggest_2022">(<a href="#ref-latour_biggest_2022" role="doc-biblioref">2022</a>)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">May 2</td>
<td style="text-align: left;">Dobbs decision leaked</td>
<td style="text-align: left;">Gerstein <span class="citation" data-cites="gerstein_supreme_2022">(<a href="#ref-gerstein_supreme_2022" role="doc-biblioref">2022</a>)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Jun.&nbsp;24</td>
<td style="text-align: left;">Dobbs decision released</td>
<td style="text-align: left;">Latour and Crisp <span class="citation" data-cites="latour_biggest_2022">(<a href="#ref-latour_biggest_2022" role="doc-biblioref">2022</a>)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Aug.&nbsp;4</td>
<td style="text-align: left;">U.S. declares monkeypox emergency</td>
<td style="text-align: left;">Bullock et al. <span class="citation" data-cites="bullock_major_nodate">(<a href="#ref-bullock_major_nodate" role="doc-biblioref">n.d.</a>)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Aug.&nbsp;8</td>
<td style="text-align: left;">Mar-a-Lago Raid</td>
<td style="text-align: left;">Latour and Crisp <span class="citation" data-cites="latour_biggest_2022">(<a href="#ref-latour_biggest_2022" role="doc-biblioref">2022</a>)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Oct.</td>
<td style="text-align: left;">Russia nuclear weapon rhetoric spike</td>
<td style="text-align: left;">Perplexity AI <span class="citation" data-cites="perplexity_ai_list_2025">(<a href="#ref-perplexity_ai_list_2025" role="doc-biblioref">2025a</a>)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Nov.&nbsp;9</td>
<td style="text-align: left;">Midterm Elections</td>
<td style="text-align: left;">Latour and Crisp <span class="citation" data-cites="latour_biggest_2022">(<a href="#ref-latour_biggest_2022" role="doc-biblioref">2022</a>)</span></td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="table-2-major-events-by-state-in-2022-bullock_major_nodate" class="level4">
<h4 class="anchored" data-anchor-id="table-2-major-events-by-state-in-2022-bullock_major_nodate"><strong>Table 2</strong>: Major Events by State in 2022 <span class="citation" data-cites="bullock_major_nodate">(<a href="#ref-bullock_major_nodate" role="doc-biblioref">Bullock et al., n.d.</a>)</span></h4>
<div id="66f8904b" class="cell" data-execution_count="5">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="5">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 14%">
<col style="width: 8%">
<col style="width: 76%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">State</th>
<th style="text-align: left;">Date</th>
<th style="text-align: left;">Event</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Alabama</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">N.A.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Arkansas</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">N.A.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">California</td>
<td style="text-align: left;">May 23</td>
<td style="text-align: left;">State threatens mandatory water restrictions owing to drought</td>
</tr>
<tr class="even">
<td style="text-align: left;">—</td>
<td style="text-align: left;">Jul.&nbsp;1</td>
<td style="text-align: left;">CNN reports Cal. man with monkeypox diagnosis urging people to get vaccinated</td>
</tr>
<tr class="odd">
<td style="text-align: left;">—</td>
<td style="text-align: left;">Jul.&nbsp;24</td>
<td style="text-align: left;">Oak Fire reported to have burned 12,000 acres in California</td>
</tr>
<tr class="even">
<td style="text-align: left;">—</td>
<td style="text-align: left;">Jul.&nbsp;27</td>
<td style="text-align: left;">Case of monkeypox reported in an infant</td>
</tr>
<tr class="odd">
<td style="text-align: left;">—</td>
<td style="text-align: left;">Aug.&nbsp;4</td>
<td style="text-align: left;">Kaiser Foundation reports on a case of monkeypox diagnosis</td>
</tr>
<tr class="even">
<td style="text-align: left;">—</td>
<td style="text-align: left;">Aug.&nbsp;5</td>
<td style="text-align: left;">Monkeypox guidance reported by LA Times</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hawaii</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">N.A.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Indiana</td>
<td style="text-align: left;">Jul.&nbsp;28</td>
<td style="text-align: left;">Monkeypox cases reported to include women and children</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Maryland</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">N.A.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Massachusetts</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">N.A.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Rhode Island</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">N.A.</td>
</tr>
<tr class="even">
<td style="text-align: left;">S. Dakota</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">N.A.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Tennessee</td>
<td style="text-align: left;">Jun.&nbsp;13</td>
<td style="text-align: left;">Nashville Electric asks consumers to conserve electricity during heat wave</td>
</tr>
</tbody>
</table>
<p>Note: Reporting of major events by state on or around the periods of interest. N.A. indicates no events reported from this source.</p>
</div>
</div>
<p>For a more comprehensive list of national events, see Perplexity AI <span class="citation" data-cites="perplexity_ai_list_2025 perplexity_ai_provide_2025">(<a href="#ref-perplexity_ai_list_2025" role="doc-biblioref">2025a</a>, <a href="#ref-perplexity_ai_provide_2025" role="doc-biblioref">2025b</a>)</span>.</p>
</section>
</section>
</section>
<section id="method" class="level1">
<h1>Method</h1>
<section id="python-packages" class="level2">
<h2 class="anchored" data-anchor-id="python-packages">Python Packages</h2>
<p>To clean and analyze the data for this project, we used Python <span class="citation" data-cites="python_software_foundation_notitle_2025">(<a href="#ref-python_software_foundation_notitle_2025" role="doc-biblioref">Python Software Foundation, 2025</a>)</span>, along with the following packages: IPython <span class="citation" data-cites="perez_ipython_2007">(<a href="#ref-perez_ipython_2007" role="doc-biblioref">Perez &amp; Granger, 2007</a>)</span>, Matplotlib <span class="citation" data-cites="hunter_matplotlib_2007">(<a href="#ref-hunter_matplotlib_2007" role="doc-biblioref">Hunter, 2007</a>)</span>, Numpy <span class="citation" data-cites="harris_array_2020">(<a href="#ref-harris_array_2020" role="doc-biblioref">Harris et al., 2020</a>)</span>, Pandas <span class="citation" data-cites="the_pandas_development_team_pandas_2020">(<a href="#ref-the_pandas_development_team_pandas_2020" role="doc-biblioref">The Pandas Development Team, 2020</a>)</span>, Pytrends <span class="citation" data-cites="hogue_pytrends_2023">(<a href="#ref-hogue_pytrends_2023" role="doc-biblioref">Hogue &amp; Burton, 2023</a>)</span>, Scipy <span class="citation" data-cites="virtanen_scipy_2020">(<a href="#ref-virtanen_scipy_2020" role="doc-biblioref">Virtanen et al., 2020</a>)</span>, Seaborn <span class="citation" data-cites="waskom_seaborn_2021">(<a href="#ref-waskom_seaborn_2021" role="doc-biblioref">Waskom, 2021</a>)</span>, Sklearn <span class="citation" data-cites="buitinck_api_2013">(<a href="#ref-buitinck_api_2013" role="doc-biblioref">Buitinck et al., 2013</a>)</span>, Statsmodels <span class="citation" data-cites="seabold_statsmodels_2010">(<a href="#ref-seabold_statsmodels_2010" role="doc-biblioref">Seabold &amp; Perktold, 2010</a>)</span>, and Tabulate <span class="citation" data-cites="astanin_python-tabulate_2022">(<a href="#ref-astanin_python-tabulate_2022" role="doc-biblioref">Astanin, 2022</a>)</span>.</p>
</section>
<section id="datasets-measures" class="level2">
<h2 class="anchored" data-anchor-id="datasets-measures">Datasets &amp; Measures</h2>
<section id="cdc-household-pulse-survey" class="level3">
<h3 class="anchored" data-anchor-id="cdc-household-pulse-survey"><em>CDC Household Pulse Survey</em></h3>
<p>We analyzed data from the Centers for Disease Control and Prevention bi-weekly report on anxiety and depressive symptoms <span class="citation" data-cites="centers_for_disease_control_and_prevention_indicators_2023">(<a href="#ref-centers_for_disease_control_and_prevention_indicators_2023" role="doc-biblioref">2023</a>)</span>. Survey data was made available by the Computer and Information Sciences Department at Willamette University.</p>
<p>The CDC compiled this dataset from responses to the Household Pulse Survey. To measure depressive symptoms, the CDC used a modified two-item Patient Health Questionnaire scale <span class="citation" data-cites="national_center_for_health_statistics_anxiety_2025">(<a href="#ref-national_center_for_health_statistics_anxiety_2025" role="doc-biblioref">National Center for Health Statistics, 2025</a>)</span>. To measure anxiety symptoms, the CDC used a modified two-item Generalized Anxiety Disorder scale <span class="citation" data-cites="national_center_for_health_statistics_anxiety_2025">(<a href="#ref-national_center_for_health_statistics_anxiety_2025" role="doc-biblioref">National Center for Health Statistics, 2025</a>)</span>. The resulting <em>value</em> represents the percentage of adults with anxiety and/or depressive symptoms exceeding a certain threshold.</p>
<p>The CDC dataset contains three types of indicators:</p>
<ul>
<li>Symptoms of Anxiety Disorder</li>
<li>Symptoms of Depressive Disorder</li>
<li>Symptoms of Anxiety Disorder or Depressive Disorder</li>
</ul>
<p>For the purposes of our analysis, the response variable we chose was <em>Symptoms of Anxiety Disorder or Depressive Disorder</em>, which is the percentage of adults who exceeded the measure threshold for symptomatic expression of anxiety <strong>or</strong> depression. This value gives us a more robust understanding of the effects of the <em>Dobbs</em> decision on the target populations than either anxiety or depression would alone.</p>
<blockquote class="blockquote">
<h4 id="missingness" class="anchored">Missingness</h4>
<p>The CDC dataset shows the percentage of adults reporting anxious and/or depressive symptoms during specific time periods, with data aggregated by group and subgroup (e.g., state of residence, gender identity, age group, etc.). Missingness occurred across various groups and subgroups, and was correlated only with the time period. For all time periods, anxiety/depression data was either not missing at all, or was completely missing, with no independent variable (such as age, state, etc.) accounting for missingness. As such, we concluded that the pattern of missingness is <strong>Missing Completely At Random (MCAR)</strong> and discarded rows with missing values during the cleaning step.</p>
</blockquote>
</section>
<section id="google-search-trends" class="level3">
<h3 class="anchored" data-anchor-id="google-search-trends"><em>Google Search Trends</em></h3>
<p>To supplement our analysis, we collected keyword search data from <a href="https://trends.google.com/">Google Trends</a>. We queried Google search data for the keyword “abortion,” both nationwide and for the states listed under State Political Leanings. This data was collected on November 8, 2025, and includes the period from January 1, 2022 to December 31, 2022 <span class="citation" data-cites="google_trends_alabama_nodate google_trends_arkansas_nodate google_trends_california_nodate google_trends_hawaii_nodate google_trends_indiana_nodate google_trends_maryland_nodate google_trends_massachusetts_nodate google_trends_rhode_nodate google_trends_south_nodate google_trends_tennessee_nodate google_trends_united_nodate">(<a href="#ref-google_trends_alabama_nodate" role="doc-biblioref">Google Trends, n.d.-a</a>, <a href="#ref-google_trends_arkansas_nodate" role="doc-biblioref">n.d.-b</a>, <a href="#ref-google_trends_california_nodate" role="doc-biblioref">n.d.-c</a>, <a href="#ref-google_trends_hawaii_nodate" role="doc-biblioref">n.d.-d</a>, <a href="#ref-google_trends_indiana_nodate" role="doc-biblioref">n.d.-e</a>, <a href="#ref-google_trends_maryland_nodate" role="doc-biblioref">n.d.-f</a>, <a href="#ref-google_trends_massachusetts_nodate" role="doc-biblioref">n.d.-g</a>, <a href="#ref-google_trends_rhode_nodate" role="doc-biblioref">n.d.-h</a>, <a href="#ref-google_trends_south_nodate" role="doc-biblioref">n.d.-i</a>, <a href="#ref-google_trends_tennessee_nodate" role="doc-biblioref">n.d.-j</a>, <a href="#ref-google_trends_united_nodate" role="doc-biblioref">n.d.-k</a>)</span>.</p>
</section>
<section id="abortion-restrictions" class="level3">
<h3 class="anchored" data-anchor-id="abortion-restrictions"><em>Abortion Restrictions</em></h3>
<p>We obtained abortion restriction data from The Kaiser Family Foundation, a non-profit organization that provides non-partisan health policy assessments <span class="citation" data-cites="kaiser_family_foundation_abortion_2025">(<a href="#ref-kaiser_family_foundation_abortion_2025" role="doc-biblioref">2025</a>)</span>. Abortion restrictions are significant to this analysis because they form the nexus between state political leanings and the impact of <em>Dobbs v. Jackson</em> on anxiety and depression within the respective states, as described below.</p>
</section>
<section id="state-political-leanings" class="level3">
<h3 class="anchored" data-anchor-id="state-political-leanings"><em>State Political Leanings</em></h3>
<p>State political leaning information obtained from a non-partisan newspaper, The Hill, in an article that ranked state legislatures from most to least conservative <span class="citation" data-cites="dress_here_2022">(<a href="#ref-dress_here_2022" role="doc-biblioref">Dress, 2022</a>)</span>. We selected states listed in the top 5 most conservative (<em>conservative</em>) and the top 5 least conservative (<em>liberal</em>) as reported on December 6, 2022 (<strong><a href="#table-3-political-leaning-by-state">Table 3</a></strong>).</p>
<section id="table-3-political-leaning-by-state" class="level4">
<h4 class="anchored" data-anchor-id="table-3-political-leaning-by-state"><strong>Table 3</strong>: Political Leaning by State</h4>
<div id="5a3cfd4b" class="cell" data-execution_count="6">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="6">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Conservative</th>
<th style="text-align: left;">Liberal</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Alabama</td>
<td style="text-align: left;">Massachusetts</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tennessee</td>
<td style="text-align: left;">Hawaii</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Indiana</td>
<td style="text-align: left;">Rhode Island</td>
</tr>
<tr class="even">
<td style="text-align: left;">South Dakota</td>
<td style="text-align: left;">California</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Arkansas</td>
<td style="text-align: left;">Maryland</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Each state in the conservative group was confirmed to have “banned” abortion, while each state in the liberal group was confirmed to allow abortion “near viability” or “no gestational limit” <span class="citation" data-cites="kaiser_family_foundation_abortion_2025">(<a href="#ref-kaiser_family_foundation_abortion_2025" role="doc-biblioref">Kaiser Family Foundation, 2025</a>)</span>. States are organized in descending order from most conservative and liberal, respectively.</p>
</section>
</section>
</section>
</section>
<section id="procedure" class="level1">
<h1>Procedure</h1>
<section id="search-trends-analysis" class="level2">
<h2 class="anchored" data-anchor-id="search-trends-analysis">Search Trends Analysis</h2>
<p>We used the Google Search Trends data to corroborate the periods of time during which abortion was top of mind in the states of interest. The Trends data shows a spike in abortion-related search queries in both conservative and liberal states during the periods of interest. As expected, searches for “abortion” spiked during the leak and the release of the <em>Dobbs</em> decision (<strong><a href="#fig.-1.-google-search-trends-plot">Fig. 1.</a></strong>).</p>
<section id="fig.-1.-google-search-trends-plot" class="level4">
<h4 class="anchored" data-anchor-id="fig.-1.-google-search-trends-plot"><strong>Fig. 1.</strong> Google Search Trends Plot</h4>
<div id="99099720" class="cell" data-execution_count="8">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Sort regions alphabetically to display in legend</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>sorted_categories <span class="op">=</span> <span class="bu">sorted</span>(trends[<span class="st">'Region'</span>].unique())</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>trends[<span class="st">'Region'</span>] <span class="op">=</span> pd.Categorical(trends[<span class="st">'Region'</span>], categories<span class="op">=</span>sorted_categories, ordered<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the Seaborn line plot with faceting</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>g <span class="op">=</span> sns.relplot(</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>    data<span class="op">=</span>trends,</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>    x<span class="op">=</span><span class="st">'date'</span>,</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    y<span class="op">=</span><span class="st">'abortion'</span>,</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    hue <span class="op">=</span> <span class="st">'Region'</span>,</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>    kind<span class="op">=</span><span class="st">'line'</span>,</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    height<span class="op">=</span><span class="dv">4</span>,</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>    aspect<span class="op">=</span><span class="fl">1.5</span>,</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>    linewidth <span class="op">=</span> <span class="fl">0.5</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Iterate through each subplot to customize x-axis</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax <span class="kw">in</span> g.axes.flat:</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Set x-axis limits based on min/max of data</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>    min_date <span class="op">=</span> trends[<span class="st">'date'</span>].<span class="bu">min</span>()</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>    max_date <span class="op">=</span> trends[<span class="st">'date'</span>].<span class="bu">max</span>()</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>    ax.set_xlim(min_date, max_date)</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Format x-axis to show only month and year</span></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>    ax.xaxis.set_major_formatter(mdates.DateFormatter(<span class="st">'%b %Y'</span>))</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Rotate x-axis labels by 45 degrees</span></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> label <span class="kw">in</span> ax.get_xticklabels():</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>        label.set_rotation(<span class="dv">45</span>)</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>        label.set_horizontalalignment(<span class="st">'right'</span>)</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a><span class="co"># Specify the dates for the vertical lines</span></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>date1 <span class="op">=</span> pd.to_datetime(<span class="st">'2022-05-02'</span>) <span class="co"># May 2, 2022</span></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>date2 <span class="op">=</span> pd.to_datetime(<span class="st">'2022-06-24'</span>) <span class="co"># June 24, 2022</span></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a><span class="co"># Add the vertical lines to the last active axis ('ax' from the loop)</span></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>line1 <span class="op">=</span> ax.axvline(</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>    x<span class="op">=</span>date1, </span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>    color<span class="op">=</span><span class="st">'red'</span>, </span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>    linestyle<span class="op">=</span><span class="st">':'</span>, </span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>    label<span class="op">=</span><span class="ss">f'Event 1: </span><span class="sc">{</span>date1<span class="sc">.</span>strftime(<span class="st">"%Y-%m-</span><span class="sc">%d</span><span class="st">"</span>)<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>line2 <span class="op">=</span> ax.axvline(</span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>    x<span class="op">=</span>date2, </span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>    color<span class="op">=</span><span class="st">'green'</span>, </span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>    linestyle<span class="op">=</span><span class="st">':'</span>, </span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>    label<span class="op">=</span><span class="ss">f'Event 2: </span><span class="sc">{</span>date2<span class="sc">.</span>strftime(<span class="st">"%Y-%m-</span><span class="sc">%d</span><span class="st">"</span>)<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a><span class="co"># Clear any existing seaborn legends from the axes first</span></span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax <span class="kw">in</span> g.axes.flat:</span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> ax.legend_ <span class="kw">is</span> <span class="kw">not</span> <span class="va">None</span>:</span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a>        ax.legend_.remove()</span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a><span class="co"># Manually create a legend</span></span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the labels for the seaborn plot data (Region names)</span></span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a>seaborn_handles <span class="op">=</span> <span class="bu">list</span>(g._legend_data.values())</span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a>seaborn_labels <span class="op">=</span> <span class="bu">list</span>(g._legend_data.keys())</span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the labels for the custom vertical lines</span></span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a>custom_handles <span class="op">=</span> [line1, line2]</span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a>custom_labels <span class="op">=</span> [<span class="st">'Dobbs Leak, May 2, 2022'</span>, <span class="st">'Dobbs Decision, June 24, 2022'</span>]</span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine all labels into single lists</span></span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a>all_handles <span class="op">=</span> seaborn_handles <span class="op">+</span> custom_handles</span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a>all_labels <span class="op">=</span> seaborn_labels <span class="op">+</span> custom_labels</span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a><span class="co"># Add a unified legend to the figure</span></span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a>g.figure.legend(</span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a>    handles<span class="op">=</span>all_handles,</span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a>    labels<span class="op">=</span>all_labels,</span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a>    loc<span class="op">=</span><span class="st">"upper left"</span>,           <span class="co"># Anchor the upper left of the legend box</span></span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a>    bbox_to_anchor<span class="op">=</span>(<span class="dv">1</span>, <span class="dv">1</span>),      <span class="co"># to the upper right of the figure area</span></span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a>    title<span class="op">=</span><span class="st">'Events'</span>,             <span class="co"># Set the combined legend title</span></span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a>    frameon<span class="op">=</span><span class="va">False</span>               <span class="co"># Remove the legend box frame</span></span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a>g.<span class="bu">set</span>(</span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a>    xlabel <span class="op">=</span> <span class="st">'Date'</span>,</span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a>    ylabel <span class="op">=</span> <span class="st">'Prevalence of "abortion" Keyword Search'</span></span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a>g.fig.suptitle(<span class="st">'Google Trends Graph of "abortion" Keyword Search Over Time'</span>)</span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a>g.figure.tight_layout() </span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="red-state-blue-state-mental-state_files/figure-html/cell-9-output-1.png" width="986" height="382" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="exploratory-data-analysis" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-data-analysis">Exploratory Data Analysis</h2>
<p>The CDC dataset included values of anxiety and depression aggregated by distinct time periods. To identify which period included meaningful data points, we narrowed our search to time periods in relation to the <em>Dobbs v. Jackson</em> decision, which was leaked on May 2, 2022 and released by the Supreme Court on June 24, 2022. To account for variance in anxiety and depressive scores from general issues, we included scores from before and after the <em>Dobbs</em> decision (<strong><a href="#table-4-periods-of-interest">Table 4</a></strong>). In the course of our exploratory data analysis, we graphed the available data for 2022 grouped by conservative and liberal states (<strong><a href="#fig.-2.-plots-of-anxiety-depression-scores-by-conservative-and-liberal-states">Fig. 2.</a></strong>), then by average score per political leaning (<strong><a href="#fig.-3.-plot-of-average-anxiety-depression-scores">Fig. 3.</a></strong>).</p>
<section id="table-4-periods-of-interest" class="level4">
<h4 class="anchored" data-anchor-id="table-4-periods-of-interest"><strong>Table 4</strong>: Periods of Interest</h4>
<div id="a8218a2a" class="cell" data-execution_count="9">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="9">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Event</th>
<th style="text-align: left;">Event Date</th>
<th style="text-align: left;">CDC Data Time Period</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><em>Dobbs Leak</em></td>
<td style="text-align: left;">May 2, 2022</td>
<td style="text-align: left;">Apr 27 - May 9, 2022</td>
</tr>
<tr class="even">
<td style="text-align: left;"><em>Before Dobbs</em></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">Jun 1 - Jun 13, 2022</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><em>Dobbs Decision</em></td>
<td style="text-align: left;">Jun 24, 2022</td>
<td style="text-align: left;">Jun 29 - Jul 11, 2022</td>
</tr>
<tr class="even">
<td style="text-align: left;"><em>After Dobbs</em></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">Jul 27 - Aug 8, 2022</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
</section>
</section>
<section id="results" class="level1">
<h1>Results</h1>
<section id="data-analysis-and-interpretation" class="level2">
<h2 class="anchored" data-anchor-id="data-analysis-and-interpretation">Data Analysis and Interpretation</h2>
<section id="fig.-2.-plots-of-anxiety-depression-scores-by-conservative-and-liberal-states" class="level4">
<h4 class="anchored" data-anchor-id="fig.-2.-plots-of-anxiety-depression-scores-by-conservative-and-liberal-states"><strong>Fig. 2.</strong> Plots of Anxiety / Depression Scores by Conservative and Liberal States</h4>
<div id="508097b9" class="cell" data-execution_count="10">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create cols for month and year</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>cdc_data.loc[:, <span class="st">'year_end'</span>] <span class="op">=</span> cdc_data[<span class="st">'time_period_end_date'</span>].dt.year</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>cdc_data.loc[:, <span class="st">'month_end'</span>] <span class="op">=</span> cdc_data[<span class="st">'time_period_end_date'</span>].dt.month</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>states <span class="op">=</span> {</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'conservative'</span>: [<span class="st">'Alabama'</span>, <span class="st">'Tennessee'</span>, <span class="st">'Indiana'</span>, <span class="st">'South Dakota'</span>, <span class="st">'Arkansas'</span>],</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">'liberal'</span>: [<span class="st">'Massachusetts'</span>, <span class="st">'Hawaii'</span>, <span class="st">'Rhode Island'</span>, <span class="st">'California'</span>, <span class="st">'Maryland'</span>]</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>dfs <span class="op">=</span> {}</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a><span class="co"># filter for anxiety OR depressive symptoms</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>filtered_data <span class="op">=</span> cdc_data[cdc_data[<span class="st">'symptoms_of'</span>] <span class="op">==</span> <span class="st">'Anxiety Disorder or Depressive Disorder'</span>]</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a><span class="co"># group data by subgroup (state), year, and month</span></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>grp_state_year_month <span class="op">=</span> filtered_data.groupby([<span class="st">'subgroup'</span>, <span class="st">'year_end'</span>, <span class="st">'month_end'</span>], as_index<span class="op">=</span><span class="va">False</span>)[<span class="st">'value'</span>].mean()</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>leanings <span class="op">=</span> [<span class="st">'conservative'</span>, <span class="st">'liberal'</span>]</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a><span class="co"># create one FacetGrid for conservative states and one for liberal states</span></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> leaning <span class="kw">in</span> leanings:</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"Anxiety and Depression in </span><span class="sc">{</span>leaning<span class="sc">.</span>title()<span class="sc">}</span><span class="ss"> States, 2022"</span>)</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>    facet_states <span class="op">=</span> states[leaning]</span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a>    state_data <span class="op">=</span> grp_state_year_month[</span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a>        (grp_state_year_month[<span class="st">'subgroup'</span>].isin(facet_states)) <span class="op">&amp;</span> </span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a>        (grp_state_year_month[<span class="st">'year_end'</span>] <span class="op">==</span> <span class="dv">2022</span>)</span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a>    ].copy()</span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a>    <span class="co"># record political leaning</span></span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a>    state_data.loc[:, <span class="st">'politics'</span>] <span class="op">=</span> leaning</span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a>    <span class="co"># save a copy of dataset in dfs dictionary for future charts</span></span>
<span id="cb2-36"><a href="#cb2-36" aria-hidden="true" tabindex="-1"></a>    dfs[leaning] <span class="op">=</span> state_data.copy()</span>
<span id="cb2-37"><a href="#cb2-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-38"><a href="#cb2-38" aria-hidden="true" tabindex="-1"></a>    <span class="co"># FacetGrid of states</span></span>
<span id="cb2-39"><a href="#cb2-39" aria-hidden="true" tabindex="-1"></a>    g <span class="op">=</span> sns.FacetGrid(</span>
<span id="cb2-40"><a href="#cb2-40" aria-hidden="true" tabindex="-1"></a>        state_data,</span>
<span id="cb2-41"><a href="#cb2-41" aria-hidden="true" tabindex="-1"></a>        col<span class="op">=</span><span class="st">'subgroup'</span>,</span>
<span id="cb2-42"><a href="#cb2-42" aria-hidden="true" tabindex="-1"></a>        col_order<span class="op">=</span>facet_states</span>
<span id="cb2-43"><a href="#cb2-43" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb2-44"><a href="#cb2-44" aria-hidden="true" tabindex="-1"></a>    g.<span class="bu">map</span>(sns.lineplot, <span class="st">'month_end'</span>, <span class="st">'value'</span>)</span>
<span id="cb2-45"><a href="#cb2-45" aria-hidden="true" tabindex="-1"></a>    g.<span class="bu">set</span>(</span>
<span id="cb2-46"><a href="#cb2-46" aria-hidden="true" tabindex="-1"></a>        xticks <span class="op">=</span> np.arange(<span class="dv">1</span>,<span class="dv">13</span>,<span class="dv">1</span>),</span>
<span id="cb2-47"><a href="#cb2-47" aria-hidden="true" tabindex="-1"></a>        xlabel <span class="op">=</span> <span class="st">'Month'</span>,</span>
<span id="cb2-48"><a href="#cb2-48" aria-hidden="true" tabindex="-1"></a>        ylabel <span class="op">=</span> <span class="st">'Anxiety/Depression'</span></span>
<span id="cb2-49"><a href="#cb2-49" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb2-50"><a href="#cb2-50" aria-hidden="true" tabindex="-1"></a>    g.set_titles(<span class="st">"</span><span class="sc">{col_name}</span><span class="st">"</span>)</span>
<span id="cb2-51"><a href="#cb2-51" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> ax <span class="kw">in</span> g.axes.flat:</span>
<span id="cb2-52"><a href="#cb2-52" aria-hidden="true" tabindex="-1"></a>        line1 <span class="op">=</span> ax.axvline(x<span class="op">=</span><span class="fl">5.07</span>, color<span class="op">=</span><span class="st">'r'</span>, linestyle<span class="op">=</span><span class="st">':'</span>)</span>
<span id="cb2-53"><a href="#cb2-53" aria-hidden="true" tabindex="-1"></a>        line2 <span class="op">=</span> ax.axvline(x<span class="op">=</span><span class="fl">6.8</span>, color<span class="op">=</span><span class="st">'g'</span>, linestyle<span class="op">=</span><span class="st">':'</span>)</span>
<span id="cb2-54"><a href="#cb2-54" aria-hidden="true" tabindex="-1"></a>        ax.axhline(y<span class="op">=</span><span class="dv">30</span>, color<span class="op">=</span><span class="st">'grey'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, linewidth<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb2-55"><a href="#cb2-55" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb2-56"><a href="#cb2-56" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Get the labels for the custom vertical lines</span></span>
<span id="cb2-57"><a href="#cb2-57" aria-hidden="true" tabindex="-1"></a>    custom_handles <span class="op">=</span> [line1, line2]</span>
<span id="cb2-58"><a href="#cb2-58" aria-hidden="true" tabindex="-1"></a>    custom_labels <span class="op">=</span> [<span class="st">'Dobbs Leak, May 2, 2022'</span>, <span class="st">'Dobbs Decision, June 24, 2022'</span>] </span>
<span id="cb2-59"><a href="#cb2-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-60"><a href="#cb2-60" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Add a unified legend to the figure</span></span>
<span id="cb2-61"><a href="#cb2-61" aria-hidden="true" tabindex="-1"></a>    g.figure.legend(</span>
<span id="cb2-62"><a href="#cb2-62" aria-hidden="true" tabindex="-1"></a>        handles<span class="op">=</span>custom_handles,</span>
<span id="cb2-63"><a href="#cb2-63" aria-hidden="true" tabindex="-1"></a>        labels<span class="op">=</span>custom_labels,</span>
<span id="cb2-64"><a href="#cb2-64" aria-hidden="true" tabindex="-1"></a>        loc<span class="op">=</span><span class="st">"upper left"</span>,</span>
<span id="cb2-65"><a href="#cb2-65" aria-hidden="true" tabindex="-1"></a>        bbox_to_anchor<span class="op">=</span>(<span class="dv">1</span>, <span class="dv">1</span>),</span>
<span id="cb2-66"><a href="#cb2-66" aria-hidden="true" tabindex="-1"></a>        title<span class="op">=</span><span class="st">'Events'</span>,</span>
<span id="cb2-67"><a href="#cb2-67" aria-hidden="true" tabindex="-1"></a>        frameon<span class="op">=</span><span class="va">False</span></span>
<span id="cb2-68"><a href="#cb2-68" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb2-69"><a href="#cb2-69" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb2-70"><a href="#cb2-70" aria-hidden="true" tabindex="-1"></a>    plt.show()</span>
<span id="cb2-71"><a href="#cb2-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-72"><a href="#cb2-72" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">'</span><span class="ch">\n</span><span class="st">'</span>)</span>
<span id="cb2-73"><a href="#cb2-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-74"><a href="#cb2-74" aria-hidden="true" tabindex="-1"></a>all_state_data <span class="op">=</span> pd.concat(dfs.values())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Anxiety and Depression in Conservative States, 2022</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="red-state-blue-state-mental-state_files/figure-html/cell-11-output-2.png" width="1703" height="286" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>

Anxiety and Depression in Liberal States, 2022</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="red-state-blue-state-mental-state_files/figure-html/cell-11-output-4.png" width="1703" height="286" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
</code></pre>
</div>
</div>
<p>Note: The horizontal line at <em>y = 30</em> is included to contrast average anxiety and depressive symptoms by political leaning in each group of states. As can be observed, most of the conservative states average scores at or above 30, while most of the liberal states converged around 30. One interpretation of this is that conservatives experience higher rates of anxiety and depressive symptoms independent of events, while liberals experience greater variability in response to events.</p>
</section>
<section id="fig.-3.-plot-of-average-anxiety-depression-scores" class="level4">
<h4 class="anchored" data-anchor-id="fig.-3.-plot-of-average-anxiety-depression-scores"><strong>Fig. 3.</strong> Plot of Average Anxiety / Depression Scores</h4>
<div id="1e3bebf2" class="cell" data-execution_count="11">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>palette <span class="op">=</span> {</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">'conservative'</span>: <span class="st">'tab:red'</span>,</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'liberal'</span>: <span class="st">'tab:blue'</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>g <span class="op">=</span> sns.lineplot(</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>    all_state_data,</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>    x <span class="op">=</span> <span class="st">'month_end'</span>,</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>    y <span class="op">=</span> <span class="st">'value'</span>,</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>    hue <span class="op">=</span> <span class="st">'politics'</span>,</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>    palette <span class="op">=</span> palette</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>g.set_xticks(np.arange(<span class="dv">1</span>,<span class="dv">13</span>,<span class="dv">1</span>))</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Month'</span>)</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Anxiety/Depression'</span>)</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Anxiety and Depression Trends for </span><span class="ch">\n</span><span class="st">Top 5 Conservative and Top 5 Liberal States (2022)'</span>)</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>line1 <span class="op">=</span> g.axvline(</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>    x<span class="op">=</span><span class="fl">5.07</span>, </span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>    color<span class="op">=</span><span class="st">'red'</span>, </span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>    linestyle<span class="op">=</span><span class="st">':'</span></span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>line2 <span class="op">=</span> g.axvline(</span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>    x<span class="op">=</span><span class="fl">6.8</span>, </span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>    color<span class="op">=</span><span class="st">'green'</span>, </span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a>    linestyle<span class="op">=</span><span class="st">':'</span></span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a><span class="co"># manually create a legend</span></span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a>h1, l1 <span class="op">=</span> g.get_legend_handles_labels()</span>
<span id="cb6-31"><a href="#cb6-31" aria-hidden="true" tabindex="-1"></a>g.legend().remove()</span>
<span id="cb6-32"><a href="#cb6-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-33"><a href="#cb6-33" aria-hidden="true" tabindex="-1"></a>custom_handles <span class="op">=</span> [line1, line2]</span>
<span id="cb6-34"><a href="#cb6-34" aria-hidden="true" tabindex="-1"></a>custom_labels <span class="op">=</span> [<span class="st">'Dobbs Leak, May 2, 2022'</span>, <span class="st">'Dobbs Decision, June 24, 2022'</span>] </span>
<span id="cb6-35"><a href="#cb6-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-36"><a href="#cb6-36" aria-hidden="true" tabindex="-1"></a><span class="co"># combine all labels into single lists</span></span>
<span id="cb6-37"><a href="#cb6-37" aria-hidden="true" tabindex="-1"></a>all_handles <span class="op">=</span> h1 <span class="op">+</span> custom_handles</span>
<span id="cb6-38"><a href="#cb6-38" aria-hidden="true" tabindex="-1"></a>all_labels <span class="op">=</span> [<span class="st">'Conservative States'</span>, <span class="st">'Liberal States'</span>] <span class="op">+</span> custom_labels</span>
<span id="cb6-39"><a href="#cb6-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-40"><a href="#cb6-40" aria-hidden="true" tabindex="-1"></a><span class="co"># add a unified legend to the figure</span></span>
<span id="cb6-41"><a href="#cb6-41" aria-hidden="true" tabindex="-1"></a>g.figure.legend(</span>
<span id="cb6-42"><a href="#cb6-42" aria-hidden="true" tabindex="-1"></a>    handles <span class="op">=</span> all_handles,</span>
<span id="cb6-43"><a href="#cb6-43" aria-hidden="true" tabindex="-1"></a>    labels <span class="op">=</span> all_labels,</span>
<span id="cb6-44"><a href="#cb6-44" aria-hidden="true" tabindex="-1"></a>    loc <span class="op">=</span> <span class="st">"lower right"</span>,</span>
<span id="cb6-45"><a href="#cb6-45" aria-hidden="true" tabindex="-1"></a>    bbox_to_anchor <span class="op">=</span> (<span class="fl">0.95</span>, <span class="fl">0.15</span>),</span>
<span id="cb6-46"><a href="#cb6-46" aria-hidden="true" tabindex="-1"></a>    borderaxespad <span class="op">=</span> <span class="dv">0</span>,</span>
<span id="cb6-47"><a href="#cb6-47" aria-hidden="true" tabindex="-1"></a>    title <span class="op">=</span> <span class="va">False</span>,</span>
<span id="cb6-48"><a href="#cb6-48" aria-hidden="true" tabindex="-1"></a>    frameon <span class="op">=</span> <span class="va">True</span></span>
<span id="cb6-49"><a href="#cb6-49" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-50"><a href="#cb6-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-51"><a href="#cb6-51" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="red-state-blue-state-mental-state_files/figure-html/cell-12-output-1.png" width="631" height="467" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong><a href="#fig.-3.-plot-of-average-anxiety-depression-scores">Fig. 3.</a></strong> reveals a strong upward trend in anxiety and depression scores immediately following the <em>Dobbs</em> leak and through the <em>Dobbs</em> decision. We therefore conclude that the peak following the Dobbs Leak represents the effect of the leak, while the following peak represents the effect of the decision.</p>
</section>
</section>
<section id="multiple-regression" class="level2">
<h2 class="anchored" data-anchor-id="multiple-regression">Multiple Regression</h2>
<section id="identification-of-variables" class="level3">
<h3 class="anchored" data-anchor-id="identification-of-variables">Identification of Variables</h3>
</section>
<section id="variable-1-time-period" class="level3">
<h3 class="anchored" data-anchor-id="variable-1-time-period"><em>Variable 1: Time Period</em></h3>
<p>Given our findings in <strong><a href="#fig.-3.-plot-of-average-anxiety-depression-scores">Fig. 3</a></strong>, we have identified the two peaks between May and July as indicators of the effects of the Dobbs Leak and Dobbs Decision, respectively, on anxiety and depressive symptoms (<strong><a href="#table-5-adjusted-periods-of-interest">Table 5</a></strong>).</p>
<p>To construct a linear regression model, we assigned a binary indicator to the period of interest (<em>0</em> = <em>“Not” Dobbs</em>, <em>1</em> = <em>Dobbs</em>).</p>
</section>
<section id="variable-2-political-leaning" class="level3">
<h3 class="anchored" data-anchor-id="variable-2-political-leaning"><em>Variable 2: Political Leaning</em></h3>
<p>As shown in <strong><a href="#fig.-3.-plot-of-average-anxiety-depression-scores">Fig. 3</a></strong>, our analysis focuses on the difference in anxiety and depression-related trends for conservative vs.&nbsp;liberal states. For the purposes of analysis, we are representing state political leanings as binary variables (<em>0</em> = liberal, <em>1</em> = conservative).</p>
<section id="table-5-adjusted-periods-of-interest" class="level4">
<h4 class="anchored" data-anchor-id="table-5-adjusted-periods-of-interest"><strong>Table 5</strong>: Adjusted Periods of Interest</h4>
<div id="47c8d879" class="cell" data-execution_count="12">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="12">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Event</th>
<th style="text-align: left;">CDC Time Period</th>
<th style="text-align: left;">Classification</th>
<th style="text-align: right;">Binary Assignment</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><em>Before Dobbs</em></td>
<td style="text-align: left;">Apr 27 - May 9, 2022</td>
<td style="text-align: left;">Not <em>Dobbs</em></td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;"><em>Dobbs Leak</em></td>
<td style="text-align: left;">Jun 1 - Jun 13, 2022</td>
<td style="text-align: left;"><em>Dobbs</em></td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><em>Dobbs Decision</em></td>
<td style="text-align: left;">Jun 29 - Jul 11, 2022</td>
<td style="text-align: left;"><em>Dobbs</em></td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;"><em>After Dobbs</em></td>
<td style="text-align: left;">Jul 27 - Aug 8, 2022</td>
<td style="text-align: left;">Not <em>Dobbs</em></td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
</section>
<section id="multiple-regression-model" class="level3">
<h3 class="anchored" data-anchor-id="multiple-regression-model">Multiple Regression Model</h3>
<div id="ac42f6a1" class="cell" data-execution_count="14">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print multiple regression information</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> np.array(df[[<span class="st">'dobbs'</span>, <span class="st">'cons'</span>]])</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> LinearRegression()</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>model.fit(X, df[<span class="st">'value'</span>])</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>coefs <span class="op">=</span> np.<span class="bu">round</span>(model.coef_, decimals<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>r2_score <span class="op">=</span> model.score(X, df[<span class="st">'value'</span>])</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> df[[<span class="st">'dobbs'</span>, <span class="st">'cons'</span>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>We constructed a multiple regression model based on these two variables. Our coefficients were <strong>3.07 and 2.06</strong> and our intercept was <strong>29.2</strong>. Our R^2 score was <strong>0.17</strong>.</p>
</section>
<section id="check-for-linearity" class="level3">
<h3 class="anchored" data-anchor-id="check-for-linearity">Check for Linearity</h3>
<p>Our VIF test returned a value of <strong>1.33</strong>. As such, we conclude that our model does not have multicollinearity. Our residuals plot suggests the data are linear and that we have equal variance for all x values (<strong><a href="#fig.-4.-residuals-plot">Fig. 4.</a></strong>). Our QQ plot suggests our model’s residuals are evenly distributed (<strong><a href="#fig.-5.-qq-plot">Fig. 5.</a></strong>), with possible outliers at the low and high ends (e.g., -2, 2). To maintain parody between conservative and liberal states, we chose to retain these outliers. Having confirmed that we passed the checks for linearity, we constructed a multiple regression model (<strong><a href="#fig.-6.-multiple-regression-plot">Fig. 6.</a></strong>).</p>
<section id="fig.-4.-residuals-plot" class="level4">
<h4 class="anchored" data-anchor-id="fig.-4.-residuals-plot"><strong>Fig. 4.</strong> Residuals Plot</h4>
<div id="1b13bd66" class="cell" data-execution_count="16">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create residual plot</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>y_pred <span class="op">=</span> model.predict(X)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>residuals <span class="op">=</span> df[<span class="st">'value'</span>] <span class="op">-</span> y_pred</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>residual_plot <span class="op">=</span> PredictionErrorDisplay.from_predictions(</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>    df[<span class="st">'value'</span>],</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>    y_pred,</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>    kind<span class="op">=</span><span class="st">'residual_vs_predicted'</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Residuals Plot'</span>)</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="red-state-blue-state-mental-state_files/figure-html/cell-17-output-1.png" width="596" height="449" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="fig.-5.-qq-plot" class="level4">
<h4 class="anchored" data-anchor-id="fig.-5.-qq-plot"><strong>Fig. 5.</strong> QQ Plot</h4>
<div id="542af35c" class="cell" data-execution_count="17">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create QQ plot</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> sm.qqplot(</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>    residuals,</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    line<span class="op">=</span><span class="st">'45'</span>,</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    fit<span class="op">=</span><span class="va">True</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'QQ Plot'</span>)</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="red-state-blue-state-mental-state_files/figure-html/cell-18-output-1.png" width="587" height="449" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="fig.-6.-multiple-regression-plot" class="level4">
<h4 class="anchored" data-anchor-id="fig.-6.-multiple-regression-plot"><strong>Fig. 6.</strong> Multiple Regression Plot</h4>
<div id="807270fc" class="cell" data-execution_count="18">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>palette <span class="op">=</span> {</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>    <span class="dv">1</span>: <span class="st">'tab:red'</span>,</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>    <span class="dv">0</span>: <span class="st">'tab:blue'</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>g <span class="op">=</span> sns.lmplot(</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>    df,</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>    x<span class="op">=</span><span class="st">'dobbs'</span>,</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>    y<span class="op">=</span><span class="st">'value'</span>,</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>    hue<span class="op">=</span><span class="st">'cons'</span>,</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>    palette <span class="op">=</span> palette,</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>    scatter_kws <span class="op">=</span> {<span class="st">'s'</span>: <span class="dv">10</span>}</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Access the axes object from the FacetGrid</span></span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> g.axes[<span class="dv">0</span>, <span class="dv">0</span>] </span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Create custom legend handles and labels (if needed)</span></span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a><span class="co"># For lmplot with hue, the handles and labels are usually derived from the hue variable</span></span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a>handles, labels <span class="op">=</span> ax.get_legend_handles_labels()</span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a>labels <span class="op">=</span> [<span class="st">'Liberal'</span>, <span class="st">'Conservative'</span>]</span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a>g.legend.remove()</span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a>plt.legend(</span>
<span id="cb10-26"><a href="#cb10-26" aria-hidden="true" tabindex="-1"></a>    handles,</span>
<span id="cb10-27"><a href="#cb10-27" aria-hidden="true" tabindex="-1"></a>    labels,</span>
<span id="cb10-28"><a href="#cb10-28" aria-hidden="true" tabindex="-1"></a>    loc <span class="op">=</span> <span class="st">'upper right'</span>,</span>
<span id="cb10-29"><a href="#cb10-29" aria-hidden="true" tabindex="-1"></a>    bbox_to_anchor<span class="op">=</span>(<span class="fl">0.7</span>, <span class="dv">1</span>),</span>
<span id="cb10-30"><a href="#cb10-30" aria-hidden="true" tabindex="-1"></a>    title <span class="op">=</span> <span class="st">'Political Leaning'</span>    </span>
<span id="cb10-31"><a href="#cb10-31" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-32"><a href="#cb10-32" aria-hidden="true" tabindex="-1"></a>plt.xticks(np.arange(<span class="dv">0</span>, <span class="dv">2</span>, <span class="dv">1</span>))</span>
<span id="cb10-33"><a href="#cb10-33" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Is Dobbs (0 = No, 1 = Yes)'</span>)</span>
<span id="cb10-34"><a href="#cb10-34" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Percent of Adults with Anxiety or Depression'</span>)</span>
<span id="cb10-35"><a href="#cb10-35" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"M. Reg. Plot of Depression / Anxiety, Politics x Dobbs"</span>)</span>
<span id="cb10-36"><a href="#cb10-36" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="red-state-blue-state-mental-state_files/figure-html/cell-19-output-1.png" width="479" height="490" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="independent-samples-t-test" class="level3">
<h3 class="anchored" data-anchor-id="independent-samples-t-test">Independent Samples t-Test</h3>
<section id="table-6-descriptive-statistic-and-t-test-results" class="level4">
<h4 class="anchored" data-anchor-id="table-6-descriptive-statistic-and-t-test-results"><strong>Table 6</strong>: Descriptive Statistic and t-Test Results</h4>
<div id="242fe2fd" class="cell" data-execution_count="19">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>conservative_data <span class="op">=</span> dfs[<span class="st">'conservative'</span>]</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>liberal_data <span class="op">=</span> dfs[<span class="st">'liberal'</span>]</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Descriptive Stats</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>con_mean <span class="op">=</span> np.mean(conservative_data[<span class="st">'value'</span>])</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>con_sd <span class="op">=</span> np.std(conservative_data[<span class="st">'value'</span>])</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>lib_mean <span class="op">=</span> np.mean(liberal_data[<span class="st">'value'</span>])</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>lib_sd <span class="op">=</span> np.std(liberal_data[<span class="st">'value'</span>])</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform independent samples t-test</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> stats.ttest_ind(conservative_data[<span class="st">'value'</span>], liberal_data[<span class="st">'value'</span>], equal_var<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>t_statistic <span class="op">=</span> result.statistic</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>p_value <span class="op">=</span> result.pvalue</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>degrees_freedom <span class="op">=</span> result.df</span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Interpret the results</span></span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a>alpha <span class="op">=</span> <span class="fl">0.05</span></span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> p_value <span class="op">&lt;</span> alpha:</span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a>    decision <span class="op">=</span> <span class="st">"reject the null hypothesis. There is a statistically significant difference in means."</span></span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a><span class="cf">else</span>:</span>
<span id="cb11-25"><a href="#cb11-25" aria-hidden="true" tabindex="-1"></a>    decision <span class="op">=</span> <span class="st">"fail to reject the null hypothesis. No statistically significant difference in means."</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div id="1a993bf9" class="cell" data-execution_count="20">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="20">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: left;">Group</th>
<th style="text-align: right;"><strong><em>M</em></strong></th>
<th style="text-align: right;"><strong><em>SD</em></strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Anxiety / Depression Score</td>
<td style="text-align: left;">Conservative</td>
<td style="text-align: right;">33.85</td>
<td style="text-align: right;">4.96</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">Liberal</td>
<td style="text-align: right;">31.38</td>
<td style="text-align: right;">3.38</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="7f92dbb6" class="cell" data-execution_count="21">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="21">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Test</th>
<th style="text-align: right;"><strong><em>t</em></strong></th>
<th style="text-align: right;"><strong><em>df</em></strong></th>
<th style="text-align: right;"><strong><em>p</em></strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Independent Samples t-Test</td>
<td style="text-align: right;">3.16</td>
<td style="text-align: right;">118</td>
<td style="text-align: right;">0.002</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Given the <em>p</em> value, we reject the null hypothesis. There is a statistically significant difference in means.</p>
</section>
</section>
</section>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>Our analysis shows a clear difference in anxiety and depressive symptoms between populations living in conservative states compared to those in liberal states. In <strong><a href="#fig.-3.-plot-of-average-anxiety-depression-scores">Fig. 3</a></strong>, we visualized these differences, concluding that conservative states report higher average levels of anxiety and depression than liberal states. We conclude that <em>Dobbs v. Jackson</em> Supreme Court case had a clear effect on populations in both conservative and liberal states.</p>
<p>To understand whether these effects were differentially associated with political leanings, we constructed a multi-linear regression model (<strong><a href="#fig.-6.-multiple-regression-plot">Fig. 6</a></strong>). Our model indicated that the <em>Dobbs Leak</em> and <em>Dobbs Decision</em> produced a greater increase in anxiety and depressive symptoms in conservative states compared to liberal states.</p>
<p>Given the regression findings, we then performed an independent samples t-Test to confirm that these differences were statistically significant. The results showed that survey respondents in conservative states (<strong><em>M</em></strong> = 33.85, <strong><em>SD</em></strong> = 4.96) reported significantly higher anxiety and depressive symptom scores compared to respondents from liberal states (<strong><em>M</em></strong> = 31.38, <strong><em>SD</em></strong> = 3.38), <em>t</em>(<em>118</em>) = 3.16, <em>p</em> = 0.002 (<strong><a href="#table-6-descriptive-statistic-and-t-test-results">Table 6</a></strong>).</p>
<section id="limitations" class="level2">
<h2 class="anchored" data-anchor-id="limitations">Limitations</h2>
<p>The CDC dataset has missing data during the periods of interest and included periods of time outside the periods of interest. For example, the <em>Dobbs</em> decision was leaked on May 2, 2022, and the data we have grouped anxiety and depression ratings from April 27 to May 9, 2022.</p>
<p>Another limitation is the impossibility of ruling out other events as a source of variance in reported anxiety and depression scores. Though we make a strong case that the <em>Dobbs</em> decision is the likely driver of these scores, it may be the case that political concerns other than abortion or cost of living may partially account for these differences. Finally, our conservative data contained a possible outlier in South Dakota, whose anxiety scores appear to fall well below those of other conservative states (<strong><a href="#fig.-2.-plots-of-anxiety-depression-scores-by-conservative-and-liberal-states">Fig. 2.</a></strong>).</p>
</section>
<section id="references" class="level2">




</section>
</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-astanin_python-tabulate_2022" class="csl-entry" role="listitem">
Astanin, S. (2022). <em>Python-tabulate: <span>Pretty</span>-print tabular data in <span>Python</span></em>. <a href="https://github.com/astanin/python-tabulate">https://github.com/astanin/python-tabulate</a>
</div>
<div id="ref-buitinck_api_2013" class="csl-entry" role="listitem">
Buitinck, L., Louppe, G., Blondel, M., Pedregosa, F., Mueller, A., Grisel, O., Niculae, V., Prettenhofer, P., Gramfort, A., Grobler, J., Layton, R., Vanderplas, J., Joly, A., Holt, B., &amp; Varoquaux, G. (2013). <em><span>API</span> design for machine learning software: Experiences from the scikit-learn project</em>. arXiv. <a href="https://doi.org/10.48550/arXiv.1309.0238">https://doi.org/10.48550/arXiv.1309.0238</a>
</div>
<div id="ref-bullock_major_nodate" class="csl-entry" role="listitem">
Bullock, J., Haddow, G., &amp; Coppola, D. (n.d.). Major events 2022. <em>Homeland Security and Emergency Management</em>. Retrieved November 24, 2025, from <a href="https://hsem.elsevier.com/index.php/2022-major-events/">https://hsem.elsevier.com/index.php/2022-major-events/</a>
</div>
<div id="ref-centers_for_disease_control_and_prevention_indicators_2023" class="csl-entry" role="listitem">
Centers for Disease Control and Prevention. (2023). <em>Indicators of <span>Anxiety</span> or <span>Depression</span> <span>Based</span> on <span>Reported</span> <span>Frequency</span> of <span>Symptoms</span> <span>During</span> <span>Last</span> 7 <span>Days</span></em>. <a href="https://data.cdc.gov/National-Center-for-Health-Statistics/Indicators-of-Anxiety-or-Depression-Based-on-Repor/8pt5-q6wp/about_data">https://data.cdc.gov/National-Center-for-Health-Statistics/Indicators-of-Anxiety-or-Depression-Based-on-Repor/8pt5-q6wp/about_data</a>
</div>
<div id="ref-dress_here_2022" class="csl-entry" role="listitem">
Dress, B. (2022). Here are the 50 legislatures ranked from most to least conservative [Text]. In <em>The Hill</em>. <a href="https://thehill.com/homenews/state-watch/3763498-here-are-the-50-legislatures-ranked-from-most-to-least-conservative/">https://thehill.com/homenews/state-watch/3763498-here-are-the-50-legislatures-ranked-from-most-to-least-conservative/</a>
</div>
<div id="ref-fredrickson_obergefell_nodate" class="csl-entry" role="listitem">
Fredrickson, C., &amp; Wurman, I. (n.d.). Obergefell v. <span>Hodges</span>. In <em>National Constitution Center – constitutioncenter.org</em>. Retrieved November 28, 2025, from <a href="https://constitutioncenter.org/the-constitution/supreme-court-case-library/obergefell-v-hodges">https://constitutioncenter.org/the-constitution/supreme-court-case-library/obergefell-v-hodges</a>
</div>
<div id="ref-gerstein_supreme_2022" class="csl-entry" role="listitem">
Gerstein, J. (2022). Supreme <span>Court</span> has voted to overturn abortion rights, draft opinion shows. In <em>POLITICO</em>. <a href="https://www.politico.com/news/2022/05/02/supreme-court-abortion-draft-opinion-00029473">https://www.politico.com/news/2022/05/02/supreme-court-abortion-draft-opinion-00029473</a>
</div>
<div id="ref-google_trends_alabama_nodate" class="csl-entry" role="listitem">
Google Trends. (n.d.-a). Alabama search trends for abortion from 1/1/2022 to 12/31/2022. In <em>Google Trends</em>. Retrieved November 9, 2025, from <a href="https://trends.google.com/trends/explore?date=2022-01-01%202022-12-31&amp;geo=US-AL&amp;q=abortion&amp;hl=en-US">https://trends.google.com/trends/explore?date=2022-01-01%202022-12-31&amp;geo=US-AL&amp;q=abortion&amp;hl=en-US</a>
</div>
<div id="ref-google_trends_arkansas_nodate" class="csl-entry" role="listitem">
Google Trends. (n.d.-b). Arkansas search trends for abortion from 1/1/2022 to 12/31/2022. In <em>Google Trends</em>. Retrieved November 9, 2025, from <a href="https://trends.google.com/trends/explore?date=2022-01-01%202022-12-31&amp;geo=US-AR&amp;q=abortion&amp;hl=en-US">https://trends.google.com/trends/explore?date=2022-01-01%202022-12-31&amp;geo=US-AR&amp;q=abortion&amp;hl=en-US</a>
</div>
<div id="ref-google_trends_california_nodate" class="csl-entry" role="listitem">
Google Trends. (n.d.-c). California search trends for abortion from 1/1/2022 to 12/31/2022. In <em>Google Trends</em>. Retrieved November 9, 2025, from <a href="https://trends.google.com/trends/explore?date=2022-01-01%202022-12-31&amp;geo=US-CA&amp;q=abortion&amp;hl=en-US">https://trends.google.com/trends/explore?date=2022-01-01%202022-12-31&amp;geo=US-CA&amp;q=abortion&amp;hl=en-US</a>
</div>
<div id="ref-google_trends_hawaii_nodate" class="csl-entry" role="listitem">
Google Trends. (n.d.-d). Hawaii search trends for abortion from 1/1/2022 to 12/31/2022. In <em>Google Trends</em>. Retrieved November 9, 2025, from <a href="https://trends.google.com/trends/explore?date=2022-01-01%202022-12-31&amp;geo=US-HI&amp;q=abortion&amp;hl=en-US">https://trends.google.com/trends/explore?date=2022-01-01%202022-12-31&amp;geo=US-HI&amp;q=abortion&amp;hl=en-US</a>
</div>
<div id="ref-google_trends_indiana_nodate" class="csl-entry" role="listitem">
Google Trends. (n.d.-e). Indiana search trends for abortion from 1/1/2022 to 12/31/2022. In <em>Google Trends</em>. Retrieved November 9, 2025, from <a href="https://trends.google.com/trends/explore?date=2022-01-01%202022-12-31&amp;geo=US-IN&amp;q=abortion&amp;hl=en-US">https://trends.google.com/trends/explore?date=2022-01-01%202022-12-31&amp;geo=US-IN&amp;q=abortion&amp;hl=en-US</a>
</div>
<div id="ref-google_trends_maryland_nodate" class="csl-entry" role="listitem">
Google Trends. (n.d.-f). Maryland search trends for abortion from 1/1/2022 to 12/31/2022. In <em>Google Trends</em>. Retrieved November 9, 2025, from <a href="https://trends.google.com/trends/explore?date=2022-01-01%202022-12-31&amp;geo=US-MD&amp;q=abortion&amp;hl=en-US">https://trends.google.com/trends/explore?date=2022-01-01%202022-12-31&amp;geo=US-MD&amp;q=abortion&amp;hl=en-US</a>
</div>
<div id="ref-google_trends_massachusetts_nodate" class="csl-entry" role="listitem">
Google Trends. (n.d.-g). Massachusetts search trends for abortion from 1/1/2022 to 12/31/2022. In <em>Google Trends</em>. Retrieved November 9, 2025, from <a href="https://trends.google.com/trends/explore?date=2022-01-01%202022-12-31&amp;geo=US-MA&amp;q=abortion&amp;hl=en-US">https://trends.google.com/trends/explore?date=2022-01-01%202022-12-31&amp;geo=US-MA&amp;q=abortion&amp;hl=en-US</a>
</div>
<div id="ref-google_trends_rhode_nodate" class="csl-entry" role="listitem">
Google Trends. (n.d.-h). Rhode <span>Island</span> search trends for abortion from 1/1/2022 to 12/31/2022. In <em>Google Trends</em>. Retrieved November 9, 2025, from <a href="https://trends.google.com/trends/explore?date=2022-01-01%202022-12-31&amp;geo=US-RI&amp;q=abortion&amp;hl=en-US">https://trends.google.com/trends/explore?date=2022-01-01%202022-12-31&amp;geo=US-RI&amp;q=abortion&amp;hl=en-US</a>
</div>
<div id="ref-google_trends_south_nodate" class="csl-entry" role="listitem">
Google Trends. (n.d.-i). South <span>Dakota</span> search trends for abortion from 1/1/2022 to 12/31/2022. In <em>Google Trends</em>. Retrieved November 9, 2025, from <a href="https://trends.google.com/trends/explore?date=2022-01-01%202022-12-31&amp;geo=US-SD&amp;q=abortion&amp;hl=en-US">https://trends.google.com/trends/explore?date=2022-01-01%202022-12-31&amp;geo=US-SD&amp;q=abortion&amp;hl=en-US</a>
</div>
<div id="ref-google_trends_tennessee_nodate" class="csl-entry" role="listitem">
Google Trends. (n.d.-j). Tennessee search trends for abortion from 1/1/2022 to 12/31/2022. In <em>Google Trends</em>. Retrieved November 9, 2025, from <a href="https://trends.google.com/trends/explore?date=2022-01-01%202022-12-31&amp;geo=US-TN&amp;q=abortion&amp;hl=en-US">https://trends.google.com/trends/explore?date=2022-01-01%202022-12-31&amp;geo=US-TN&amp;q=abortion&amp;hl=en-US</a>
</div>
<div id="ref-google_trends_united_nodate" class="csl-entry" role="listitem">
Google Trends. (n.d.-k). United <span>States</span> search trends for abortion from 1/1/2022 to 12/31/2022. In <em>Google Trends</em>. Retrieved November 9, 2025, from <a href="https://trends.google.com/trends/explore?date=2022-01-01%202022-12-31&amp;geo=US&amp;q=abortion&amp;hl=en-US">https://trends.google.com/trends/explore?date=2022-01-01%202022-12-31&amp;geo=US&amp;q=abortion&amp;hl=en-US</a>
</div>
<div id="ref-google_trends_united_nodate-1" class="csl-entry" role="listitem">
Google Trends. (n.d.-l). United <span>States</span> search trends for <span>Russia</span> nuclear from 1/1/2022 to 12/31/2022. In <em>Google Trends</em>. Retrieved November 9, 2025, from <a href="https://trends.google.com/trends/explore?date=2022-01-01%202022-12-31&amp;geo=US&amp;q=russia%20nuclear&amp;hl=en-US">https://trends.google.com/trends/explore?date=2022-01-01%202022-12-31&amp;geo=US&amp;q=russia%20nuclear&amp;hl=en-US</a>
</div>
<div id="ref-harris_array_2020" class="csl-entry" role="listitem">
Harris, C. R., Millman, K. J., Walt, S. J. van der, Gommers, R., Virtanen, P., Cournapeau, D., Wieser, E., Taylor, J., Berg, S., Smith, N. J., Kern, R., Picus, M., Hoyer, S., Kerkwijk, M. H. van, Brett, M., Haldane, A., Río, J. F. del, Wiebe, M., Peterson, P., … Oliphant, T. E. (2020). Array programming with <span>NumPy</span>. <em>Nature</em>, <em>585</em>(7825), 357–362. <a href="https://doi.org/10.1038/s41586-020-2649-2">https://doi.org/10.1038/s41586-020-2649-2</a>
</div>
<div id="ref-historycom_editors_dred_2009" class="csl-entry" role="listitem">
History.com Editors. (2009). Dred <span>Scott</span> <span>Case</span>. In <em>HISTORY</em>. <a href="https://www.history.com/articles/dred-scott-case">https://www.history.com/articles/dred-scott-case</a>
</div>
<div id="ref-hogue_pytrends_2023" class="csl-entry" role="listitem">
Hogue, J., &amp; Burton, D. (2023). <em>Pytrends: <span>Unofficial</span> <span>API</span> for <span>Google</span> <span>Trends</span></em>. Apache Software License.
</div>
<div id="ref-hunter_matplotlib_2007" class="csl-entry" role="listitem">
Hunter, J. D. (2007). Matplotlib: <span>A</span> <span>2D</span> <span>Graphics</span> <span>Environment</span>. <em>Computing in Science &amp; Engineering</em>, <em>9</em>(3), 90–95. <a href="https://doi.org/10.1109/MCSE.2007.55">https://doi.org/10.1109/MCSE.2007.55</a>
</div>
<div id="ref-kaiser_family_foundation_abortion_2025" class="csl-entry" role="listitem">
Kaiser Family Foundation. (2025). Abortion in the <span>United</span> <span>States</span> dashboard. In <em>KFF</em>. <a href="https://www.kff.org/womens-health-policy/abortion-in-the-u-s-dashboard/">https://www.kff.org/womens-health-policy/abortion-in-the-u-s-dashboard/</a>
</div>
<div id="ref-latour_biggest_2022" class="csl-entry" role="listitem">
Latour, A., &amp; Crisp, E. (2022). The biggest events of 2022 [Text]. In <em>The Hill</em>. <a href="https://thehill.com/homenews/noteddc/3785891-the-biggest-events-of-2022/">https://thehill.com/homenews/noteddc/3785891-the-biggest-events-of-2022/</a>
</div>
<div id="ref-national_center_for_health_statistics_anxiety_2025" class="csl-entry" role="listitem">
National Center for Health Statistics. (2025). Anxiety and depression: <span>Household</span> pulse survey, 2020-2024. <em>U.S. Census Bureau</em>. <a href="https://www.cdc.gov/nchs/covid19/pulse/mental-health.htm">https://www.cdc.gov/nchs/covid19/pulse/mental-health.htm</a>
</div>
<div id="ref-palacio_implications_2023" class="csl-entry" role="listitem">
Palacio, H. (2023). Implications of <span>Dobbs</span> v <span>Jackson</span> women’s health organization. <em>American Journal of Public Health</em>, <em>113</em>(4), 388–389. <a href="https://doi.org/10.2105/AJPH.2023.307244">https://doi.org/10.2105/AJPH.2023.307244</a>
</div>
<div id="ref-perez_ipython_2007" class="csl-entry" role="listitem">
Perez, F., &amp; Granger, B. E. (2007). <span>IPython</span>: <span>A</span> system for interactive scientific computing. <em>Computing in Science &amp; Engineering</em>, <em>9</em>(3), 21–29. <a href="https://doi.org/10.1109/MCSE.2007.53">https://doi.org/10.1109/MCSE.2007.53</a>
</div>
<div id="ref-perplexity_ai_list_2025" class="csl-entry" role="listitem">
Perplexity AI. (2025a). <em>List of major events in 2022 by month in the <span>United</span> <span>States</span></em>. Perplexity AI, Inc. <a href="https://www.perplexity.ai/search/provide-a-list-of-major-events-D8ll4ViDTEqYNDwZqkhaZg#1">https://www.perplexity.ai/search/provide-a-list-of-major-events-D8ll4ViDTEqYNDwZqkhaZg#1</a>
</div>
<div id="ref-perplexity_ai_provide_2025" class="csl-entry" role="listitem">
Perplexity AI. (2025b). <em>Provide a list of dates of key events involving the possible use of nuclear weapons by <span>Russia</span> in <span>Ukraine</span></em>. Perplexity AI, Inc. <a href="https://www.perplexity.ai/search/provide-a-list-of-dates-of-key-29pvp0NWRgSYakf6NfYh9w#3">https://www.perplexity.ai/search/provide-a-list-of-dates-of-key-29pvp0NWRgSYakf6NfYh9w#3</a>
</div>
<div id="ref-pew_research_center_public_2025" class="csl-entry" role="listitem">
Pew Research Center. (2025). <em>Public opinion on abortion</em>. <a href="https://pewrsr.ch/3WzBfPb">https://pewrsr.ch/3WzBfPb</a>
</div>
<div id="ref-python_software_foundation_notitle_2025" class="csl-entry" role="listitem">
Python Software Foundation. (2025). <a href="https://www.python.org/">https://www.python.org/</a>
</div>
<div id="ref-seabold_statsmodels_2010" class="csl-entry" role="listitem">
Seabold, S., &amp; Perktold, J. (2010). Statsmodels: <span>Econometric</span> and statistical modeling with <span>Python</span>. <em>SciPy 2010</em>. <a href="https://doi.org/10.25080/Majora-92bf1922-011">https://doi.org/10.25080/Majora-92bf1922-011</a>
</div>
<div id="ref-the_pandas_development_team_pandas_2020" class="csl-entry" role="listitem">
The Pandas Development Team. (2020). <em>Pandas</em>. Zenodo. <a href="https://doi.org/10.5281/zenodo.17229934">https://doi.org/10.5281/zenodo.17229934</a>
</div>
<div id="ref-virtanen_scipy_2020" class="csl-entry" role="listitem">
Virtanen, P., Gommers, R., Oliphant, T. E., Haberland, M., Reddy, T., Cournapeau, D., Burovski, E., Peterson, P., Weckesser, W., Bright, J., Walt, S. J. van der, Brett, M., Wilson, J., Millman, K. J., Mayorov, N., Nelson, A. R. J., Jones, E., Kern, R., Larson, E., … Mulbregt, P. van. (2020). <span>SciPy</span> 1.0: Fundamental algorithms for scientific computing in <span>Python</span>. <em>Nature Methods</em>, <em>17</em>(3), 261–272. <a href="https://doi.org/10.1038/s41592-019-0686-2">https://doi.org/10.1038/s41592-019-0686-2</a>
</div>
<div id="ref-waskom_seaborn_2021" class="csl-entry" role="listitem">
Waskom, M. L. (2021). Seaborn: <span>Statistical</span> data visualization. <em>Journal of Open Source Software</em>, <em>6</em>(60), 3021. <a href="https://doi.org/10.21105/joss.03021">https://doi.org/10.21105/joss.03021</a>
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/your_github_username\.github\.io");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 Blitz Bearcat</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>